### ISSUE TITLE
cron.d

### ISSUE THREAD

**Issue by denji** [pierreprinetti/certbot#3]
How about adding a scheduler to run periodically renew, implemented [here](https://github.com/sebble/docker-images/blob/master/letsencrypt-certbot/etc/crontab)

**Comment by pierreprinetti** [comment]
Please add some plain English for me to understand what you need.

**Comment by pierreprinetti** [comment]
In the README, [I suggest](https://github.com/pierreprinetti/certbot#renewing-certificates) a script to be called from the host crontab. I believe that container cronjobs are a sensitive object and in any case should not be used to start the main process of the container.
