### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by KristerV** [pierreprinetti/certbot#5]
It's super hard to figure out how to use but I'm determined. The limits are reached pretty fast though so how do I connect to the testing environment? https://letsencrypt.org/docs/staging-environment/

**Comment by pierreprinetti** [comment]
wow, the testing environment did not exist when I wrapped Certbot.

Certbot provides the flag `--staging` for running against the testing environment, you could add that switch to `run.sh`.

**Comment by KristerV** [comment]
I was having so much trouble with containerized dockers that I just installed it into my nginx container.. so good for now, thanks.
