### ISSUE TITLE
Renewing certificates Link is breaking

### ISSUE THREAD

**Issue by murilobsd** [pierreprinetti/certbot#6]

**Comment by dcb9** [comment]
+1

**Comment by kalkafox** [comment]
Create your own script that appends `-e renew=true` as an environment parameter and make crontab call this script.

Example derived from the documentation:

```
#!/bin/bash
docker run \
  -v nginx-certs:/etc/letsencrypt \
  -e renew=true \
  -e email="me@example.com" \
  -p 80:80 \
  -p 443:443 \
  --rm pierreprinetti/certbot:latest
```

It is important to make sure the `domains` environment is not in this docker command, because it is intended for renewal, not the creation of new certs for domains.

**Comment by urbanslug** [comment]
@mild-prowler 

So your solution led me down the right path but there are a couple of certbot issues regarding symlinks caused it to fail for me.
https://github.com/certbot/certbot/issues/3499
https://github.com/certbot/certbot/issues/3497

One has to get into to the docker container and run `certbot renew` with `--force-renewal`

So basically this:
```bash
#!/bin/bash
docker run -it \
  -v nginx-certs:/etc/letsencrypt \
  -e renew=true \
  -e email="me@example.com" \
  -p 80:80 \
  -p 443:443 \
  pierreprinetti/certbot:latest bash
```

then when in the container run `# certbot renew --force-renewal`

@pierreprinetti  I think we should have these containers take args to `certbot` to future proof from problems in certbot.
Something like `-e certbot-agrs="<certbot>, <args>"`

**Comment by patrick-motard** [comment]
I'd love to see a conclusion to this issue.

**Comment by pierreprinetti** [comment]
@patrick-motard 

> I'd love to see a conclusion to this issue.

I am not using this code anymore and I am not investing time on it at the moment. You are very welcome to submit a pull request or to fork if you like the idea of building upon this code.

**Comment by patrick-motard** [comment]
@pierreprinetti thank you for letting me know. I'm going to look into this and see if i can come up with a solution. If i find one i'll submit a PR.
